spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 1024MB

minio:
  endpoint: http://10.60.20.70:9000
  accessKey: boot-minio
  secretKey: boot-minio-secret


